#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#

export EDITOR='nvim'
export VISUAL='nvim'
export PAGER='less'

#
# Language
#

export LANG='en_US.UTF-8'
export LC_CTYPE="en_US.UTF-8"

#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

fpath=("/usr/local/bin/" $fpath)

# Set the the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )
#
export GEM_HOME=$HOME/.gem

# Go
export GOPATH=$HOME/.go

# Python
export PYTHON_HOME=$HOME/Library/Python/3.7

# Dotty
export DOTTY_HOME=$HOME/Code/vendors/dotty

# Set the list of directories that Zsh searches for programs.
path=(
  $HOME/.bin
  $HOME/.local/bin
  $HOME/.cargo/bin
  $HOME/.elan/bin
  $HOME/.gem/bin
  $GOPATH/bin
  $DOTTY_HOME/bin
  $PYTHON_HOME/bin
  /usr/local/{bin,sbin}
  /opt/local/{bin,sbin}
  $path
)

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

#
# Temporary Files
#
#
if [[ -z "$TMPDIR" ]]; then
  export TMPDIR="/tmp/zsh-$UID"
fi

if [[ ! -d "$TMPDIR" ]]; then
  mkdir "$TMPDIR"
  chmod 700 "$TMPDIR"
fi


