#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#   Romain Ruetschi <romain.ruetschi@gmail.com>
#

#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#

export EDITOR='vim'
export VISUAL=$EDITOR
export SVN_EDITOR=$EDITOR
export GIT_EDITOR=$EDITOR
export GEM_OPEN_EDITOR=$EDITOR
export PAGER='less'

#
# Language
#

# if [[ -z "$LANG" ]]; then
export LANG='en_US.UTF-8'
export LANGUAGE=$LANG
export LC_CTYPE=$LANG
# fi

# Python Virtualenv
# export WORKON_HOME=$HOME/.virtualenvs
# export PROJECT_HOME=$HOME/Projects
export VIRTUALENVWRAPPER_PYTHON=/usr/local/bin/python
source /usr/local/bin/virtualenvwrapper.sh

# Nix
# source $HOME/.nix-profile/etc/profile.d/nix.sh

# Android Dev Tools
export ANDROID_HOME=/usr/local/opt/android-sdk

# Rust
RUSTUP_PREFIX=/usr/local/rust

#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Set the list of directories that Zsh searches for programs.
path=(
  $HOME/.bin                                # Personal
  $HOME/.local/bin                          # Stack
  $HOME/.local/ghcjs                        # GHCJS
  $HOME/.rbenv/shims                        # rbenv
  $HOME/.cabal/bin                          # Cabal
  $HOME/.go/bin                             # Go
  $HOME/.local/bin                          # Local Stack binaries
  $HOME/.jenv/bin
  ./node_modules/.bin                       # node_modules binaries
  /usr/local/{bin,sbin}                     # Homebrew
  /usr/local/share/npm/bin                  # NPM
  /usr/local/texlive/2015/bin/x86_64-darwin # MacTeX 2015
  /usr/local/{rock,ooc}/bin                 # ooc
  # /usr/local/share/python                   # Python
  /usr/local/google-cloud-sdk/bin           # Google Cloud SDK
  /usr/local/ghc/bin                        # GHC
  $RUSTUP_PREFIX/bin                        # Rust
  /usr/local/mysql/bin                      # MySQL
  /usr/local/coq/bin                        # Coq
  /usr/local/activator/bin                  # Activator
  /usr/local/infer/infer/infer/bin          # Infer
  /usr/local/stack/bin                      # Stack
  /usr/local/ipfs/bin                       # IPFS
  $path

  # $HOME/.bin/emsdk                          # Emscripten
  # $HOME/.bin/emsdk/clang/3.2_64bit/bin
  # $HOME/.bin/emsdk/node/0.10.18_64bit/bin
  # $HOME/.bin/emsdk/emscripten/1.5.6
)

fpath=(
  /usr/local/share/zsh/site-functions
  /usr/local/google-cloud-sdk/completion
  $fpath
)

export DYLD_LIBRARY_PATH=/usr/local/rust/lib:$DYLD_LIBRARY_PATH

# JEnv
if which jenv > /dev/null; then eval "$(jenv init -)"; fi

# Java default file encoding
export JAVA_OPTS="-Dfile.encoding=UTF-8 $JAVA_OPTS"

# Java 8
export JAVA_HOME=$(/usr/libexec/java_home -v `cat ~/.jenv/version`)

# Go
export GOPATH=$HOME/.go

# NVM
export NVM_DIR=~/.nvm
source $(brew --prefix nvm)/nvm.sh

# Node modules path
export NODE_PATH=/usr/local/lib/node_modules:$NODE_PATH

# Rock distribution path
export ROCK_DIST=/usr/local/rock
export OOC_LIBS=/usr/local/ooc

# Urbit
export URBIT_HOME=~/Projects/urbit/urb

# Ruby
if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi

# OpenSSL Certificates
export SSL_CERT_FILE=/usr/local/opt/curl-ca-bundle/share/ca-bundle.crt

# Disable Homebrew Emojis
export HOMEBREW_NO_EMOJI=1

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

#
# Temporary Files
#

if [[ ! -d "$TMPDIR" ]]; then
  export TMPDIR="/tmp/$USER"
  mkdir -p -m 700 "$TMPDIR"
fi

TMPPREFIX="${TMPDIR%/}/zsh"
if [[ ! -d "$TMPPREFIX" ]]; then
  mkdir -p "$TMPPREFIX"
fi

# Neovim
export NVIM_TUI_ENABLE_TRUE_COLOR=1

# OPAM
eval `opam config env`

# OPAM configuration
. /Users/romac/.opam/opam-init/init.zsh > /dev/null 2> /dev/null || true

