#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#   Romain Ruetschi <romain.ruetschi@gmail.com>
#

#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#

export EDITOR='/usr/local/bin/subl -w -n'
export VISUAL=$EDITOR
export SVN_EDITOR=$EDITOR
export GIT_EDITOR=$EDITOR
export GEM_OPEN_EDITOR=$EDITOR
export PAGER='less'

#
# Language
#

# if [[ -z "$LANG" ]]; then
export LANG='en_US.UTF-8'
export LANGUAGE=$LANG
export LC_CTYPE=$LANG
# fi

# Java default file encoding
export JAVA_OPTS="-Dfile.encoding=UTF-8 $JAVA_OPTS"

# Use Java 6
# export JAVA_HOME=/System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home

# Python Virtualenv
# export WORKON_HOME=$HOME/.virtualenvs
# export PROJECT_HOME=$HOME/Projects
export VIRTUALENVWRAPPER_PYTHON=/usr/local/bin/python
source /usr/local/bin/virtualenvwrapper.sh

#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Set the list of directories that Zsh searches for programs.
path=(
  $HOME/.bin                                # Personal
  /usr/local/{bin,sbin}                     # Homebrew
  /usr/local/share/npm/bin                  # NPM
  /usr/local/texlive/2012/bin/x86_64-darwin # MacTeX 2012
  /usr/local/{rock,ooc}/bin                 # ooc
  # /usr/local/share/python                   # Python
  /usr/local/google-cloud-sdk/bin           # Google Cloud SDK
  $HOME/.rbenv/shims                        # rbenv
  $HOME/.cabal/bin                          # Cabal
  $path

  # $HOME/.bin/emsdk                          # Emscripten
  # $HOME/.bin/emsdk/clang/3.2_64bit/bin
  # $HOME/.bin/emsdk/node/0.10.18_64bit/bin
  # $HOME/.bin/emsdk/emscripten/1.5.6
)

fpath=(
  /usr/local/share/zsh/site-functions
  /usr/local/google-cloud-sdk/completion
  $fpath
)

# Go
export GOPATH=$HOME/.go

# Node modules path
export NODE_PATH=$NODE_PATH:/usr/local/share/npm/lib/node_modules

# Rock distribution path
export ROCK_DIST=/usr/local/rock
export OOC_LIBS=/usr/local/ooc

# Urbit
export URBIT_HOME=~/Projects/urbit/urb

# Ruby
if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi

# OpenSSL Certificates
export SSL_CERT_FILE=/usr/local/opt/curl-ca-bundle/share/ca-bundle.crt

# Disable Homebrew Emojis
export HOMEBREW_NO_EMOJI=1

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

#
# Temporary Files
#

if [[ ! -d "$TMPDIR" ]]; then
  export TMPDIR="/tmp/$USER"
  mkdir -p -m 700 "$TMPDIR"
fi

TMPPREFIX="${TMPDIR%/}/zsh"
if [[ ! -d "$TMPPREFIX" ]]; then
  mkdir -p "$TMPPREFIX"
fi
